[target.'cfg(target_arch = "xtensa")']
runner = "espflash flash --monitor"
rustflags = [
  # Tell the `core` library that we have atomics, even though it's not
  # specified in the target definition
  "--cfg", 'target_has_atomic="8"',
  "--cfg", 'target_has_atomic="16"',
  "--cfg", 'target_has_atomic="32"',
  "--cfg", 'target_has_atomic="ptr"',

  "-C", "link-arg=-nostartfiles",
  # Enable the atomic codegen option for Xtensa
  "-C", "target-feature=+s32c1i",
  "-C", "link-arg=-Wl,-Tlinkall.x",
  # force-frame-pointers disabled, because LLVM 16 in Rust Xtensa toolchain 1.69.0.1 introduces regression and
  # compilation was failing with:
  # Error while trying to spill A5 from class AR: Cannot scavenge register without an emergency spill slot!
  #"-C", "force-frame-pointers"
]

[target.riscv32imac-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
]

[build]
# Uncomment the target if you'd like to use automatic code hinting in your IDE
# target = "xtensa-esp32-none-elf"
# target = "xtensa-esp32s2-none-elf"
target = "xtensa-esp32s3-none-elf"
# target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = [ "core", "alloc" ]
