esp_toml_version = 1.0
firmware_images_url = "https://github.com/georgik/esp32-spooky-maze-game/releases/download/v0.3.0/"
supported_apps = ["spooky_maze"]

[spooky_maze]
chipsets = ["ESP32", "ESP32-S2", "ESP32-C3"]
image.esp32 = "spooky-wrover-kit"
image.esp32-s2 = "SINGLE_BIN_FOR_ESP32-S2.bin"
image.esp32-c3 = "SINGLE_BIN_FOR_ESP32-C3.bin"
android_app_url = ""
ios_app_url = ""

