[package]
name = "spi-dma-displayinterface"
version = "0.1.0"
edition = "2021"

[dependencies]
byte-slice-cast = { version = "0.3.5", default-features = false }
display-interface = "0.4"
display-interface-spi = "0.4"
embedded-graphics = "0.8.0"
embedded-hal = { version = "0.2", features = ["unproven"] }
embedded-dma = "0.2.0"

esp32-hal = { version = "0.16.0", optional = true }
esp32c3-hal = { version = "*", optional = true }
esp32c6-hal = { version = "*", optional = true }
esp32s2-hal = { version = "0.13.0", optional = true }
esp32s3-hal = { version = "0.13.0", optional = true }

[features]
default = []
esp32 = [ "esp32-hal" ]
esp32c3 = [ "esp32c3-hal" ]
esp32c6 = [ "esp32c6-hal" ]
esp32s2 = [ "esp32s2-hal" ]
esp32s3 = [ "esp32s3-hal" ]

