[package]
name = "spi-dma-displayinterface"
version = "0.1.0"
edition = "2021"

[dependencies]
byte-slice-cast = { version = "0.3.5", default-features = false }
display-interface = "0.4"
display-interface-spi = "0.4"
embedded-graphics = "0.8.0"
embedded-hal = { version = "0.2", features = ["unproven"] }
embedded-dma = "0.2.0"
hal = { package = "esp32s3-hal", version = "0.13.0" }
