[package]
name = "spooky_idf_rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
spooky_core = { git = "https://github.com/georgik/esp32-spooky-maze-game.git", package = "spooky-core", default-features = false, features = ["static_maze"] }
embedded-graphics = "0.8.0"
embedded-graphics-framebuf = { version = "0.3.0", git = "https://github.com/georgik/embedded-graphics-framebuf.git", branch = "feature/embedded-graphics-0.8" }
# nmea = { version = "0.6.0", default-features=false, features = ["GNSS", "GGA"] }
# esp-alloc = "0.3.0"
# heapless = "0.7.16"

[features]
default = [ ]