[target.'cfg(target_arch = "xtensa")']
runner = "espflash flash --monitor"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "link-arg=-nostartfiles",

  # enable the atomic codegen option for Xtensa
  "-C", "target-feature=+s32c1i",

  # tell the core library have atomics even though it's not specified in the target definition
  "--cfg", "target_has_atomic_load_store",
  "--cfg", 'target_has_atomic_load_store="8"',
  "--cfg", 'target_has_atomic_load_store="16"',
  "--cfg", 'target_has_atomic_load_store="32"',
  "--cfg", 'target_has_atomic_load_store="ptr"',
  # enable cas
  "--cfg", "target_has_atomic",
  "--cfg", 'target_has_atomic="8"',
  "--cfg", 'target_has_atomic="16"',
  "--cfg", 'target_has_atomic="32"',
  "--cfg", 'target_has_atomic="ptr"',
]

[build]
# Uncomment the target if you'd like to use automatic code hinting in your IDE
# target = "xtensa-esp32-none-elf"
 target = "xtensa-esp32s2-none-elf"
#target = "xtensa-esp32s3-none-elf"
# target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = [ "core", "alloc" ]
