name: CI for ESP32-S3

on:
  push:
    paths:
      - "esp32-s3/**"
      - "spooky-core/**"
      - "spooky-embedded/**"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust (Xtensa)
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          version: '1.82.0'
          buildtargets: esp32s3
          ldproxy: false

      - name: Enable caching
        uses: Swatinem/rust-cache@v2

      - name: Run checks sequentially for all boards
        working-directory: esp32-s3
        run: |
          # Define the list of boards to build
          boards=("esp32-s3-box" "esp32-s3-box-3" "esp32-s3-usb-otg" "m5stack-cores3")

          # Perform common checks
          echo "Running common checks"
          cargo fmt --all -- --check --color always
          cargo clippy --release --all-features --workspace -- -D warnings

          # Iterate through each board and build
          for board in "${boards[@]}"; do
            echo "Building for board: $board"
            cargo build --release --features "$board"
          done
