name: CI for ESP32-C6

on:
#  push:
#    paths:
#      - "esp32-c6/**"
#      - "spooky-core/**"
#      - "spooky-embedded/**"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  rust-checks:
    name: Rust Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust (Xtensa)
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          version: '1.82.0'
          buildtargets: esp32c6
          ldproxy: false

      - name: Enable caching
        uses: Swatinem/rust-cache@v2

      - name: Run checks sequentially for all boards
        working-directory: esp32-c6
        run: |
          # Define the list of boards to build
          boards=("esp32-c6-devkitc-1" "waveshare-esp32-c6-lcd-1-47")

          # Perform common checks
          echo "Running common checks"
          cargo fmt --all -- --check --color always

          # Iterate through each board and build
          for board in "${boards[@]}"; do
            echo "Building for board: $board"
            cargo clippy --release --features "$board" --workspace -- -D warnings
            cargo build --release --features "$board"
          done
